#!/usr/bin/env ruby
#
# Plugin to monitor memcache statistics

case ARGV[0]
when "config"
  puts %Q{
    graph_title Memcached hits and misses
    graph_args --base 1000 -l 0
    graph_vlabel requests
    graph_category memcached
    graph_info This graph monitors the number of cache hits and misses.
    hits.label hits
    hits.info Number of cache hits
    hits.min 0
    hits.type DERIVE
    misses.label misses
    misses.info Number of cache misses
    misses.min 0
    misses.type DERIVE
    misses.draw AREA
  }.gsub!(/^\s*/, "")
when "autoconf"
  puts "yes"
else
  require "socket"

  TCPSocket.open("localhost", "11211") do |socket|
    socket.send("stats\r\n", 0)
    stats = socket.recv(4096)
    puts "hits.value #{$1}" if stats =~ /STAT get_hits (\d+)/
    puts "misses.value #{$1}" if stats =~ /STAT get_misses (\d+)/
  end
end
